service: imas-nestjs-app

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1

plugins:
  - serverless-layers
  - serverless-offline

custom:
  serverless-layers:
    layersDeploymentBucket: imas-nestjs-app-lambda-layers

package:
  individually: true
  include:
    - dist/**
  exclude:
    - node_modules/**
    - "**"

functions:
  index:
    handler: dist/index.handler
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any
